### ISSUE TITLE
build failure in intelliJ Idea

### ISSUE THREAD

**Issue by mooxiu** [yahoojp-marketing/ads-search-api-java-lib#15]
Version: 3.0.0
Device: macbook m1
Java Version: 1.17

Problem: lack of dependency for `javax.annotation`.

IDEA constantly reported problem:
> error: cannot find symbol @javax.annotation.Generated

solution might be adding dependency in `pom.xml`:
```maven
<!-- https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api -->
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.3.2</version>
</dependency>
```

**Comment by ryfukuda** [comment]
Thank you for your feedback.

We have added support for java 9 and above in version 3.0.1.

Best regards,
ryfukuda
